# Generated by Django 3.1.5 on 2021-02-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_Name', models.CharField(default='', max_length=200)),
                ('item_Price', models.FloatField(default=0.0)),
                ('item_Ingredients', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
