# Generated by Django 3.1.5 on 2021-02-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu_Items',
            new_name='Menu',
        ),
    ]
