# Generated by Django 3.1.5 on 2021-02-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='would_you_reccommend',
            new_name='would_you_reccommend_our_restaraunt',
        ),
    ]
