# Generated by Django 3.1.5 on 2021-02-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210202_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='posted_at',
            new_name='date_posted',
        ),
    ]
